name: Build

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:


jobs:
  lint:
    name: Check build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Make
        run: make BUILD=debug
