name: Lint

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:


jobs:
  lint:
    name: Check linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Update
        run: sudo apt update && sudo apt upgrade -y && sudo apt install clang clang-format
      - name: Run clang-format
        run: clang-format -i -Werror src/*.c src/*.h
