name: Test

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:


jobs:
  lint:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Run tests
        run: make test BUILD=debug
